Tip16 JavaScript code snippets deprecated
- Updated content to match new content template
- Tested JavaScript tip several times, getting errors/tests fail, code snippet may need to be updated
- Errors I got : 
1) Screenshot
       "before each" hook for "on failure":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. 

  2) Screenshot
       "after each" hook for "on failure":
     TypeError: Cannot read properties of undefined (reading 'takeScreenshot')