Tip53 Add ruby md
Tip53 Add ruby md
-  changed `rspec-expectations` to `rspec/expectations`
-  updated jquery.src library link
-  getting error: “TypeError: $.growl is not a function”
-  unable to validate due to error with growl

Needs to be done:
- [x] Escalating to @diemol for: [ENTER REASON]
- [ ] Code validated/fixed by expert, as necessary
- [ ] Edit instructions as necessary after code is validated