Tip12 Update content, code snippets deprecated
- Updated content to match new content template
- Tested JavaScript tip several times, getting errors/tests fail, code snippet may need to be updated
- Errors I got : 2 test failed (0 passed)
 1) A/B opt-out
       "before each" hook for "with cookie after visiting page":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "quit()" is called; if returning a Promise, ensure it resolves. 

  2) A/B opt-out
       "after each" hook for "with cookie after visiting page":
     TypeError: Cannot read properties of undefined (reading 'quit')